version: 2.1

orbs:
  python: circleci/python@2

jobs:
  test-python:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Run tests
          command: |
            pytest --junitxml=junit.xml || ((($? == 5)) && echo 'Did not find any tests to run.')
      - store_test_results:
          path: junit.xml

  build-package:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Build package
          command: python setup.py sdist bdist_wheel
      - store_artifacts:
          path: dist

workflows:
  build-and-test:
    jobs:
      - test-python
      - build-package:
          requires:
            - test-python